// This file is auto-generated by scripts/update-schemas.js
// Do not edit manually - your changes will be overwritten

// Schema definitions for attestation forms
export type FieldType = 'string' | 'integer' | 'array' | 'enum' | 'datetime' | 'uri' | 'object' | 'json'

export interface FormField {
  name: string
  type: FieldType
  label: string
  description?: string
  required: boolean
  placeholder?: string
  options?: (string | number)[] // for enum fields (strings or integers)
  format?: string // for validation (uri, date-time, etc.)
  pattern?: string // regex pattern for string validation
  min?: number // for integer fields
  max?: number // for integer fields
  minLength?: number // for string fields
  maxLength?: number // for string fields
  subFields?: FormField[] // for object fields with nested properties
  default?: any // default value for the field
  autoDefault?: string // auto-generate default (e.g., 'current-timestamp')
  subtype?: string // semantic subtype (e.g., 'timestamp' for integer fields)
  nested?: boolean // for object fields: true = render with container/heading, false/omitted = render flat
}

export interface AttestationSchema {
  id: string
  title: string
  description: string
  fields: FormField[]
  deployedUIDs?: Record<number, string> // chainId -> schemaUID mapping
  deployedBlocks?: Record<number, number> // chainId -> deployment block number
}

// Field definitions
const certificationFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the product, system, or organization being certified.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization that owns or governs the certified subject. For example, when certifying did:web:example.com:service:api, set organization to did:web:example.com. Leave empty when certifying an organization itself.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Software version of the certified subject.",
    "required": false,
    "placeholder": "Enter version",
    "maxLength": 50
  },
  {
    "name": "versionHW",
    "type": "string",
    "label": "Hardware Version",
    "description": "Hardware version of the certified subject, if applicable.",
    "required": false,
    "placeholder": "Enter versionhw",
    "maxLength": 50
  },
  {
    "name": "subjectURI",
    "type": "uri",
    "label": "Subject Informational URI",
    "description": "Optional URI controlled by the subject that provides mutable, human-readable metadata.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "programID",
    "type": "string",
    "label": "Program ID",
    "description": "DID of the certification program under which this certification was issued. Program release version should be included in the DID.",
    "required": true,
    "placeholder": "Enter programid",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "programURI",
    "type": "uri",
    "label": "Program Informational URI",
    "description": "Optional URI for mutable, human-readable certification program info.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "assessor",
    "type": "string",
    "label": "Assessor DID",
    "description": "DID of the authorized assessor (test lab, auditor) who evaluated the subject.",
    "required": true,
    "placeholder": "Enter assessor",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "assessorURI",
    "type": "uri",
    "label": "Assessor Informational URI",
    "description": "Optional URI with human-readable info about the assessor (e.g., homepage, credentials).",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "certificationLevel",
    "type": "string",
    "label": "Certification Level",
    "description": "Optional classification level of certification (e.g., 'Gold', 'Level 2').",
    "required": false,
    "placeholder": "Enter certificationlevel",
    "maxLength": 256
  },
  {
    "name": "outcome",
    "type": "enum",
    "label": "Outcome",
    "description": "Overall outcome of an assessment or certification. If omitted, outcome MUST be interpreted as 'pass'.",
    "required": false,
    "placeholder": "Enter outcome",
    "options": [
      "pass",
      "fail"
    ]
  },
  {
    "name": "reportURI",
    "type": "uri",
    "label": "Report URI",
    "description": "Optional URI to the certification report or assessment documentation.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "reportDigest",
    "type": "json",
    "label": "Report Digest",
    "description": "Content digest of a report for integrity verification. Paste the full JSON object.",
    "required": false,
    "placeholder": "Paste JSON object..."
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the certification was issued by the certification body.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp"
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Unix timestamp (in seconds) when the certification becomes effective.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional expiration timestamp (in seconds).",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp"
  }
]

const commonFields: FormField[] = []

const endorsementFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the entity being endorsed or approved.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization. Use this when endorsing a service or resource that belongs to an organization (e.g., endorsing did:web:example.com:service:api, set organization to did:web:example.com). Leave empty when endorsing an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Semantic version of the endorsed subject (e.g., '1.2.3'). Optional - leave empty if endorsing the subject generally rather than a specific version.",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50,
    "pattern": "^\\d+\\.\\d+\\.\\d+$"
  },
  {
    "name": "policyURI",
    "type": "uri",
    "label": "Policy URI",
    "description": "Optional URI pointing to the criteria or process used for formal approvals.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const keyBindingFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID to which this key is bound.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "keyId",
    "type": "string",
    "label": "Key Identifier",
    "description": "DID representing this key. If using did:key or did:pkh:eip155, publicKeyJwk is optional.",
    "required": true,
    "placeholder": "Enter keyid",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "publicKeyJwk",
    "type": "json",
    "label": "Public Key (JWK)",
    "description": "JWK-formatted public key. Required if keyId is not a self-certifying did:key. Paste the full JWK JSON object.",
    "required": false,
    "placeholder": "Paste JSON object..."
  },
  {
    "name": "keyPurpose",
    "type": "array",
    "label": "Key Purpose",
    "description": "Permitted purposes for this key (e.g., 'authentication', 'assertionMethod', 'keyAgreement', 'capabilityInvocation', 'capabilityDelegation').",
    "required": true,
    "placeholder": "Enter keypurpose"
  },
  {
    "name": "proofs",
    "type": "array",
    "label": "Proofs",
    "description": "Array of cryptographic proofs demonstrating the subject's control over the key. Use proofPurpose='shared-control' for key binding attestations.",
    "required": true,
    "placeholder": "Enter proofs"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the key binding was issued.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Unix timestamp (in seconds) when the key binding becomes effective.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const linkedIdentifierFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the identity initiating the link (e.g., did:pkh for wallets, did:web for domains, did:handle for social accounts, did:key for keys).",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "linkedId",
    "type": "string",
    "label": "Linked Identifier",
    "description": "DID of the identity being linked (e.g., did:handle for social accounts, did:web for domains, did:pkh for wallets, did:key for keys). The DID method encodes the platform/type internally.",
    "required": true,
    "placeholder": "Enter linkedid",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "method",
    "type": "string",
    "label": "Verification Method",
    "description": "Verification method used by the attester to confirm the subject's control of the linkedId. Use 'proof' for cryptographic proofs (pop-eip712, pop-jwt, evidence-pointer). Platform authority or URL-based evidence may be used to prove control of did:handle identifiers. Custom methods are permitted.",
    "required": true,
    "placeholder": "Enter method",
    "maxLength": 64
  },
  {
    "name": "proofs",
    "type": "array",
    "label": "Proofs",
    "description": "Array of cryptographic proofs demonstrating the subject's control over the linked identifier. Use proofPurpose='shared-control' for linked identifier attestations.",
    "required": false,
    "placeholder": "Enter proofs"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const securityAssessmentFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "ID of the assessed application/contract/service. Select an ID type below and enter the proper identity.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization. Use this when assessing a service or resource that belongs to an organization (e.g., assessing did:web:example.com:service:api, set organization to did:web:example.com). Leave empty when assessing an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Semantic version of the software/code that was assessed (e.g., '1.2.3').",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50,
    "pattern": "^\\d+\\.\\d+\\.\\d+$"
  },
  {
    "name": "versionHW",
    "type": "string",
    "label": "Hardware Version",
    "description": "Hardware version of the assessed subject, if applicable.",
    "required": false,
    "placeholder": "Enter versionhw",
    "maxLength": 50
  },
  {
    "name": "payload",
    "type": "object",
    "label": "Assessment Payload",
    "description": "Assessment details. Evolvable without changing the envelope. When stored on-chain via EAS, this object is JSON-stringified.",
    "required": true,
    "subFields": [
      {
        "name": "assessmentKind",
        "type": "string",
        "label": "Assessment Kind",
        "description": "High-level category of the assessment. Registered kinds are defined in the OMA3 Assessment Kind Registry.",
        "required": true,
        "placeholder": "Enter assessmentkind",
        "maxLength": 64
      },
      {
        "name": "methodURI",
        "type": "uri",
        "label": "Methodology URI",
        "description": "Methodology / SOP documentation.",
        "required": false,
        "placeholder": "https://example.com",
        "maxLength": 256,
        "format": "uri"
      },
      {
        "name": "reportURI",
        "type": "uri",
        "label": "Report URI",
        "description": "Human-readable report location (may be mutable).",
        "required": false,
        "placeholder": "https://example.com",
        "maxLength": 256,
        "format": "uri"
      },
      {
        "name": "reportDigest",
        "type": "json",
        "label": "Report Digest",
        "description": "Content digest of a report for integrity verification. Paste the full JSON object.",
        "required": false,
        "placeholder": "Paste JSON object..."
      },
      {
        "name": "outcome",
        "type": "enum",
        "label": "Outcome",
        "description": "Overall outcome of an assessment or certification. If omitted, outcome MUST be interpreted as 'pass'.",
        "required": false,
        "placeholder": "Enter outcome",
        "options": [
          "pass",
          "fail"
        ]
      }
    ]
  },
  {
    "name": "payloadVersion",
    "type": "string",
    "label": "Payload Version",
    "description": "Semver describing the shape of the payload.",
    "required": true,
    "placeholder": "Enter payloadversion",
    "default": "1.0.0",
    "maxLength": 50
  },
  {
    "name": "payloadSpecURI",
    "type": "uri",
    "label": "Payload Specification URI",
    "description": "URI to the JSON schema specification for this attestation type.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "payloadSpecDigest",
    "type": "json",
    "label": "Payload Specification Digest",
    "description": "Integrity digest for payloadSpecURI. Paste the full JSON object.",
    "required": false,
    "placeholder": "Paste JSON object..."
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const userReviewResponseFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Reviewer ID",
    "description": "DID of the original reviewer being responded to.",
    "required": false,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "refUID",
    "type": "string",
    "label": "User Review UID",
    "description": "The UID of the user review being responded to.",
    "required": true,
    "placeholder": "Enter refuid",
    "maxLength": 66
  },
  {
    "name": "responseBody",
    "type": "string",
    "label": "Response",
    "description": "Free-form text containing the response to the review.",
    "required": true,
    "placeholder": "Enter responsebody",
    "maxLength": 500
  }
]

const userReviewFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Review Subject",
    "description": "DID of the thing being reviewed.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 256,
    "pattern": "^did:[a-z0-9]+:.+$",
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Subject Version",
    "description": "Version of the reviewed subject (e.g., app or API version).",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50,
    "pattern": "^\\d+\\.\\d+\\.\\d+$"
  },
  {
    "name": "ratingValue",
    "type": "enum",
    "label": "Rating",
    "description": "Numerical rating from 1 (worst) to 5 (best).",
    "required": true,
    "placeholder": "0",
    "options": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  {
    "name": "reviewBody",
    "type": "string",
    "label": "Review",
    "description": "Free-form text describing your experience or feedback.",
    "required": false,
    "placeholder": "Enter reviewbody",
    "maxLength": 500
  },
  {
    "name": "screenshotUrls",
    "type": "array",
    "label": "Screenshots",
    "description": "Optional screenshots showing the app during review.",
    "required": false,
    "placeholder": "Enter screenshoturls"
  },
  {
    "name": "proofs",
    "type": "array",
    "label": "Proofs",
    "description": "Array of cryptographic proofs demonstrating the reviewer used the service. Use proofPurpose='commercial-tx' for user review attestations.",
    "required": false,
    "placeholder": "Enter proofs"
  }
]

// Schema definitions
export const certificationSchema: AttestationSchema = {
  id: 'certification',
  title: 'Certification',
  description: 'Certification bodies use this attestation when a subject passes certification.',
  fields: certificationFields,
  deployedUIDs: {
    97: '0xbb9e58a64550b7956561e9c9266e0a0747fc80c40bd57bb2637be7f8f2817bf7', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x2b0d1100f7943c0c2ea29e35c1286bd860fa752124e035cafb503bb83f234805', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52415269, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 289, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const commonSchema: AttestationSchema = {
  id: 'common',
  title: 'OMA3 Common Definitions',
  description: 'Shared data types and proof structures for OMATrust schemas.',
  fields: commonFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x0000000000000000000000000000000000000000000000000000000000000000', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 0, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const endorsementSchema: AttestationSchema = {
  id: 'endorsement',
  title: 'Endorsement',
  description: 'A lightweight attestation indicating support, trust, or approval for a DID-identified subject. The \'attestationType\' field may be used to distinguish informal endorsements from formal approvals.',
  fields: endorsementFields,
  deployedUIDs: {
    97: '0xda787e2c5b89cd1b2c77d7a9565573cc89bac752e9b587f3348e85c62d606a68', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xb0cf93ef0f3feb858aa5d07a54f6589da5852883f378dfd0cae5315da1d679ac', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52288891, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 290, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const keyBindingSchema: AttestationSchema = {
  id: 'key-binding',
  title: 'Key Binding',
  description: 'Publishes a cryptographic key associated with a DID. Supports multi-purpose bindings, rotation, and revocation. Each attestation binds one key to one subject.',
  fields: keyBindingFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x290ce7f909a98f74d2356cf24102ac813555fa0bcd456f1bab17da2d92632e1d', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 291, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const linkedIdentifierSchema: AttestationSchema = {
  id: 'linked-identifier',
  title: 'Linked Identifier',
  description: 'An attestation where the attester (a trusted third party) asserts that the subject controls the linked identifier. Both subject and linkedId MUST be valid DIDs, creating a symmetric DID-to-DID link that attests two identities are owned by the same entity.',
  fields: linkedIdentifierFields,
  deployedUIDs: {
    97: '0xd6ef74f4f2f8d79a8993132577713ada1ae9ba937d8bbd69a174cd6afe6beef6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xed79388b434965a35d50573b75f4bbd6e3bc7912103c4a6ac0aff6a510ccadac', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52415311, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 292, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const securityAssessmentSchema: AttestationSchema = {
  id: 'security-assessment',
  title: 'Security Assessment',
  description: 'Use this form to record a security assessment onchain',
  fields: securityAssessmentFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x67bcc2424e3721d56e85bb650c6aba8bf7f1711d9c9a434c3afae3a22d23eed7', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 293, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const userReviewResponseSchema: AttestationSchema = {
  id: 'user-review-response',
  title: 'User Review Response',
  description: 'A response from an app owner or representative to a UserReview attestation. Uses refUID to reference the original review.',
  fields: userReviewResponseFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x53498ae8ae4928a8789e09663f44d6e3c77daeb703c3765aa184b958c3ca41be', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 294, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const userReviewSchema: AttestationSchema = {
  id: 'user-review',
  title: 'User Review',
  description: 'A flat schema for structured 1–5 star reviews of tokenized applications or digital services. Designed for onchain attestation and offchain anchoring.',
  fields: userReviewFields,
  deployedUIDs: {
    97: '0x21deb2c39c4899b39d3f4af965d455be97862c6be18ffd2c15dbd74aaf50a5f6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x7ab3911527e5e47eaab9f5a2c571060026532dde8cb4398185553053963b2a47', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52291400, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 295, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

// Export all schemas
const allSchemas: AttestationSchema[] = [
  certificationSchema,
  commonSchema,
  endorsementSchema,
  keyBindingSchema,
  linkedIdentifierSchema,
  securityAssessmentSchema,
  userReviewResponseSchema,
  userReviewSchema
]

export function getSchema(id: string): AttestationSchema | undefined {
  return allSchemas.find(schema => schema.id === id)
}

export function getSchemaIds(): string[] {
  return allSchemas.map(schema => schema.id)
}

export function getAllSchemas(): AttestationSchema[] {
  return allSchemas
}
