// This file is auto-generated by scripts/update-schemas.js
// Do not edit manually - your changes will be overwritten

// Schema definitions for attestation forms
export type FieldType = 'string' | 'integer' | 'array' | 'enum' | 'datetime' | 'uri' | 'object'

export interface FormField {
  name: string
  type: FieldType
  label: string
  description?: string
  required: boolean
  placeholder?: string
  options?: string[] // for enum fields
  format?: string // for validation (uri, date-time, etc.)
  min?: number // for integer fields
  max?: number // for integer fields
  minLength?: number // for string fields
  maxLength?: number // for string fields
  subFields?: FormField[] // for object fields with nested properties
  default?: any // default value for the field
  autoDefault?: string // auto-generate default (e.g., 'current-timestamp')
  subtype?: string // semantic subtype (e.g., 'timestamp' for integer fields)
  nested?: boolean // for object fields: true = render with container/heading, false/omitted = render flat
}

export interface AttestationSchema {
  id: string
  title: string
  description: string
  fields: FormField[]
  deployedUIDs?: Record<number, string> // chainId -> schemaUID mapping
  deployedBlocks?: Record<number, number> // chainId -> deployment block number
}

// Field definitions
const certificationFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the product, system, or organization being certified.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization. Use this when certifying a service or resource that belongs to an organization (e.g., certifying did:web:example.com:service:api, set organization to did:web:example.com). Leave empty when certifying an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "subjectOwner",
    "type": "string",
    "label": "Subject Owner ID",
    "description": "DID of the entity responsible for the subject.  If there is no owner, leave blank.",
    "required": false,
    "placeholder": "Enter subjectowner",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "subjectMetadataURI",
    "type": "uri",
    "label": "Subject Informational URI",
    "description": "Optional URI controlled by the subject that provides mutable, human-readable metadata.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "programIdentifier",
    "type": "string",
    "label": "Program ID",
    "description": "DID of the certification program under which this certification was issued. Program release version should be included in the DID.",
    "required": true,
    "placeholder": "Enter programidentifier",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "programMetadataURI",
    "type": "uri",
    "label": "Program Informational URI",
    "description": "Optional URI for mutable, human-readable certification program info.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "assessor",
    "type": "string",
    "label": "Assessor DID",
    "description": "DID of the authorized assessor (test lab, auditor) who evaluated the subject.",
    "required": true,
    "placeholder": "Enter assessor",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "assessorMetadataURI",
    "type": "uri",
    "label": "Assessor Informational URI",
    "description": "Optional URI with human-readable info about the assessor (e.g., homepage, credentials).",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "certificationLevel",
    "type": "string",
    "label": "Certification Level",
    "description": "Optional classification level of certification (e.g., 'Gold', 'Level 2').",
    "required": false,
    "placeholder": "Enter certificationlevel",
    "maxLength": 256
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Software version of the certified subject.",
    "required": false,
    "placeholder": "Enter version",
    "maxLength": 50
  },
  {
    "name": "versionHW",
    "type": "string",
    "label": "Hardware Version",
    "description": "Hardware version of the certified subject, if applicable.",
    "required": false,
    "placeholder": "Enter versionhw",
    "maxLength": 50
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Unix timestamp (in seconds) when the certification becomes effective.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional expiration timestamp (in seconds).",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Optional timestamp (in seconds) when the certification was issued.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp"
  }
]

const endorsementFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the entity being endorsed or approved.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization. Use this when endorsing a service or resource that belongs to an organization (e.g., endorsing did:web:example.com:service:api, set organization to did:web:example.com). Leave empty when endorsing an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Semantic version of the endorsed subject (e.g., '1.2.3'). Optional - leave empty if endorsing the subject generally rather than a specific version.",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50
  },
  {
    "name": "policyURI",
    "type": "uri",
    "label": "Policy URI",
    "description": "Optional URI pointing to the criteria or process used for formal approvals.",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const linkedIdentifierFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the subject (such as did:pkh for wallet addresses or did:web for web domains) that is claimed to control the linked identifier.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "linkedId",
    "type": "string",
    "label": "Linked Identifier",
    "description": "The identifier being claimed as controlled by the subject (e.g., a did:web, email address, or domain).",
    "required": true,
    "placeholder": "Enter linkedid",
    "maxLength": 256
  },
  {
    "name": "linkedIdType",
    "type": "string",
    "label": "Linked ID Type",
    "description": "Type or namespace of the linkedId being asserted. Examples: did:web (for websites), did:key (for keys), email, twitter, github, facebook, discord, telegram, lens, farcaster, or any other well-known identifier type.",
    "required": false,
    "placeholder": "Enter linkedidtype",
    "maxLength": 100
  },
  {
    "name": "method",
    "type": "enum",
    "label": "Verification Method",
    "description": "Verification method used by the attester to confirm the subject's control of the linkedId.",
    "required": true,
    "placeholder": "Enter method",
    "options": [
      "http-file",
      "dns-txt",
      "email-challenge",
      "social-post",
      "manual",
      "oauth",
      "other"
    ]
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const securityAssessmentFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "ID of the assessed application/contract/service. Select an ID type below and enter the proper identity.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Organization",
    "description": "DID of the parent organization. Use this when assessing a service or resource that belongs to an organization (e.g., assessing did:web:example.com:service:api, set organization to did:web:example.com). Leave empty when assessing an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Semantic version of the software/code that was assessed (e.g., '1.2.3').",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50
  },
  {
    "name": "payload",
    "type": "object",
    "label": "Assessment Payload",
    "description": "Assessment details. Evolvable without changing the envelope. When stored on-chain via EAS, this object is JSON-stringified.",
    "required": true,
    "subFields": [
      {
        "name": "assessmentKind",
        "type": "enum",
        "label": "Assessment Kind",
        "description": "High-level category of the assessment.",
        "required": true,
        "placeholder": "Enter assessmentkind",
        "options": [
          "pentest",
          "security-audit",
          "code-review",
          "vulnerability-scan"
        ]
      },
      {
        "name": "methodURI",
        "type": "uri",
        "label": "Methodology URI",
        "description": "Methodology / SOP documentation.",
        "required": false,
        "placeholder": "https://example.com",
        "maxLength": 256,
        "format": "uri"
      },
      {
        "name": "reportURI",
        "type": "uri",
        "label": "Report URI",
        "description": "Human-readable report location (may be mutable).",
        "required": false,
        "placeholder": "https://example.com",
        "maxLength": 256,
        "format": "uri"
      },
      {
        "name": "reportDigest",
        "type": "object",
        "label": "Report Digest",
        "description": "Content digest of the report for integrity verification.",
        "required": false,
        "subFields": [
          {
            "name": "algo",
            "type": "enum",
            "label": "Report Hash Algorithm",
            "description": "Hash algorithm used for report digest computation. Per OMATrust spec, only keccak256 and sha256 are supported.",
            "required": false,
            "placeholder": "Enter algo",
            "default": "keccak256",
            "options": [
              "keccak256",
              "sha256"
            ]
          },
          {
            "name": "hex",
            "type": "string",
            "label": "Report Hash Value",
            "description": "0x-prefixed hex digest of the canonical report bytes.",
            "required": false,
            "placeholder": "Enter hex",
            "maxLength": 200
          }
        ]
      },
      {
        "name": "outcome",
        "type": "enum",
        "label": "Assessment Outcome",
        "description": "Overall outcome of the assessment.",
        "required": false,
        "placeholder": "Enter outcome",
        "options": [
          "pass",
          "pass-with-findings",
          "fail",
          "informational"
        ]
      }
    ]
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) when the attestation was issued. Default is the current time.",
    "required": true,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp (in seconds) when the assessment becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Unix timestamp (in seconds) after which the assessment expires. Leave empty if the assessment does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

const userReviewResponseFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "Address of the original reviewer being responded to.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128
  },
  {
    "name": "responseBody",
    "type": "string",
    "label": "Response",
    "description": "Free-form text containing the response to the review.",
    "required": true,
    "placeholder": "Enter responsebody",
    "maxLength": 500
  },
  {
    "name": "datePublished",
    "type": "datetime",
    "label": "Date Published",
    "description": "Timestamp when the response was written or published, in ISO 8601 format.",
    "required": false,
    "placeholder": "2024-01-01T00:00:00Z",
    "maxLength": 50,
    "format": "date-time"
  },
  {
    "name": "anchoredDataURL",
    "type": "uri",
    "label": "Anchored Data URL",
    "description": "URI pointing to offchain response content (e.g., IPFS, Cloudinary, Arweave).",
    "required": false,
    "placeholder": "https://example.com",
    "maxLength": 256,
    "format": "uri"
  },
  {
    "name": "anchoredDataAlgorithm",
    "type": "string",
    "label": "Anchored Data Hash Algorithm",
    "description": "Hashing algorithm used for 'anchoredDataHash' (e.g., 'sha3-256').",
    "required": false,
    "placeholder": "Enter anchoreddataalgorithm",
    "maxLength": 50
  },
  {
    "name": "anchoredDataHash",
    "type": "string",
    "label": "Anchored Data Hash",
    "description": "Cryptographic hash of the content located at 'anchoredDataURL'.",
    "required": false,
    "placeholder": "Enter anchoreddatahash",
    "maxLength": 200
  },
  {
    "name": "attestationType",
    "type": "string",
    "label": "Attestation Type",
    "description": "Type identifier for this attestation (e.g., 'UserReviewResponse').",
    "required": false,
    "placeholder": "Enter attestationtype",
    "maxLength": 100
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) for when the response was submitted.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional expiration timestamp for the attestation.",
    "required": false,
    "placeholder": "0"
  }
]

const userReviewFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the thing being reviewed.",
    "required": true,
    "placeholder": "Enter subject",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "organization",
    "type": "string",
    "label": "Owning Organization",
    "description": "DID of the service organization. Use this when reviewing a service that belongs to an organization. Leave empty when reviewing an organization directly.",
    "required": false,
    "placeholder": "Enter organization",
    "maxLength": 128,
    "format": "did"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Subject Version",
    "description": "Version of the reviewed subject (e.g., app or API version).",
    "required": false,
    "placeholder": "Enter version",
    "subtype": "semver",
    "maxLength": 50
  },
  {
    "name": "summary",
    "type": "string",
    "label": "Review Summary",
    "description": "Short headline for the review (e.g., 'Loved it', 'Buggy experience').",
    "required": false,
    "placeholder": "Enter summary",
    "maxLength": 200
  },
  {
    "name": "reviewBody",
    "type": "string",
    "label": "Review",
    "description": "Free-form text describing your experience or feedback.",
    "required": false,
    "placeholder": "Enter reviewbody",
    "maxLength": 500
  },
  {
    "name": "author",
    "type": "string",
    "label": "Author ID",
    "description": "Your DID, handle, or name.",
    "required": false,
    "placeholder": "Enter author",
    "maxLength": 200
  },
  {
    "name": "ratingValue",
    "type": "integer",
    "label": "Rating",
    "description": "Numerical rating from 1 (worst) to 5 (best).",
    "required": true,
    "placeholder": "0",
    "min": 1,
    "max": 5
  },
  {
    "name": "screenshotUrls",
    "type": "array",
    "label": "Screenshots",
    "description": "Optional screenshots showing the app during review.",
    "required": false,
    "placeholder": "Enter screenshoturls"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Timestamp (in seconds) when the review was issued. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Timestamp (in seconds) when the review becomes effective. Default is the current time.",
    "required": false,
    "placeholder": "0",
    "autoDefault": "current-timestamp",
    "subtype": "timestamp",
    "min": 0
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Timestamp (in seconds) after which the review expires. Leave empty if the review does not expire.",
    "required": false,
    "placeholder": "0",
    "subtype": "timestamp",
    "min": 0
  }
]

// Schema definitions
export const certificationSchema: AttestationSchema = {
  id: 'certification',
  title: 'Certification',
  description: 'Certification bodies use this attestation when a subject passes certification.',
  fields: certificationFields,
  deployedUIDs: {
    97: '0xbb9e58a64550b7956561e9c9266e0a0747fc80c40bd57bb2637be7f8f2817bf7', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xa798698f86b62e0fa2e63cff94e7bcdf275ab015702d1e9ed85d1a95af7bff78', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52415269, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 128, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const endorsementSchema: AttestationSchema = {
  id: 'endorsement',
  title: 'Endorsement',
  description: 'A lightweight attestation indicating support, trust, or approval for a DID-identified subject. The \'attestationType\' field may be used to distinguish informal endorsements from formal approvals.',
  fields: endorsementFields,
  deployedUIDs: {
    97: '0xda787e2c5b89cd1b2c77d7a9565573cc89bac752e9b587f3348e85c62d606a68', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xa349c19677b8c98c44e176eb03e8481e700f1e50ca22cfdfb395f32243e51abe', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52288891, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 127, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const linkedIdentifierSchema: AttestationSchema = {
  id: 'linked-identifier',
  title: 'Linked Identifier',
  description: 'An attestation where the attester (a trusted third party) asserts that the subject controls the linked identifier, effectively attesting that two identities are owned by the same entity.',
  fields: linkedIdentifierFields,
  deployedUIDs: {
    97: '0xd6ef74f4f2f8d79a8993132577713ada1ae9ba937d8bbd69a174cd6afe6beef6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xd6ef74f4f2f8d79a8993132577713ada1ae9ba937d8bbd69a174cd6afe6beef6', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52415311, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 50, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const securityAssessmentSchema: AttestationSchema = {
  id: 'security-assessment',
  title: 'Security Assessment',
  description: 'Use this form to record a security assessment onchain',
  fields: securityAssessmentFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0x99eeac6a1110ac16e8abf80118ddab37cf37916e3f79f995384d034f56cd0c1c', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 126, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const userReviewResponseSchema: AttestationSchema = {
  id: 'user-review-response',
  title: 'User Review Response',
  description: 'A response from an app owner or representative to a UserReview attestation. Uses refUID to reference the original review.',
  fields: userReviewResponseFields,
  deployedUIDs: {
    97: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xb28cd01484fe76c3cd24a2df64051a281eba7724f527ed6b3d99a72c4d6293ae', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 0, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 51, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

export const userReviewSchema: AttestationSchema = {
  id: 'user-review',
  title: 'User Review',
  description: 'A flat schema for structured 1–5 star reviews of tokenized applications or digital services. Designed for onchain attestation and offchain anchoring.',
  fields: userReviewFields,
  deployedUIDs: {
    97: '0x21deb2c39c4899b39d3f4af965d455be97862c6be18ffd2c15dbd74aaf50a5f6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000', // BSC Mainnet
    66238: '0xdcc94cf54d3b13c6718c796f44d69609f459f81d80800ecc0ae3083168010571', // OMAchain Testnet
    6623: '0x0000000000000000000000000000000000000000000000000000000000000000'  // OMAchain Mainnet
  },
  deployedBlocks: {
    97: 52291400, // BSC Testnet
    56: 0, // BSC Mainnet
    66238: 125, // OMAchain Testnet
    6623: 0  // OMAchain Mainnet
  }
};

// Export all schemas
const allSchemas: AttestationSchema[] = [
  certificationSchema,
  endorsementSchema,
  linkedIdentifierSchema,
  securityAssessmentSchema,
  userReviewResponseSchema,
  userReviewSchema
]

export function getSchema(id: string): AttestationSchema | undefined {
  return allSchemas.find(schema => schema.id === id)
}

export function getSchemaIds(): string[] {
  return allSchemas.map(schema => schema.id)
}

export function getAllSchemas(): AttestationSchema[] {
  return allSchemas
}
