// This file is auto-generated by scripts/update-schemas.js
// Do not edit manually - your changes will be overwritten

// Schema definitions for attestation forms
export type FieldType = 'string' | 'integer' | 'array' | 'enum' | 'datetime' | 'uri' | 'text'

export interface FormField {
  name: string
  type: FieldType
  label: string
  description?: string
  required: boolean
  placeholder?: string
  options?: string[] // for enum fields
  format?: string // for validation (uri, date-time, etc.)
  min?: number // for integer fields
  max?: number // for integer fields
}

export interface AttestationSchema {
  id: string
  title: string
  description: string
  fields: FormField[]
  deployedUIDs?: Record<number, string> // chainId -> schemaUID mapping
  deployedBlocks?: Record<number, number> // chainId -> deployment block number
}

// Field definitions
const certificationFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the product, system, or organization being certified.",
    "required": true,
    "placeholder": "Enter subject"
  },
  {
    "name": "subjectOwner",
    "type": "string",
    "label": "Subject Owner ID",
    "description": "DID of the entity responsible for the subject.",
    "required": false,
    "placeholder": "Enter subjectowner"
  },
  {
    "name": "subjectMetadataURI",
    "type": "uri",
    "label": "Subject Informational URI",
    "description": "Optional URI controlled by the subject that provides mutable, human-readable metadata.",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "programIdentifier",
    "type": "string",
    "label": "Program ID",
    "description": "DID or URI of the certification program under which this certification was issued.",
    "required": true,
    "placeholder": "Enter programidentifier"
  },
  {
    "name": "programMetadataURI",
    "type": "uri",
    "label": "Program Informational URI",
    "description": "Optional URI for mutable, human-readable certification program info.",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "anchoredDataURL",
    "type": "uri",
    "label": "Anchored Data URL",
    "description": "Immutable URI containing the canonical certification program data (e.g., requirements, test plans).",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "anchoredDataAlgorithm",
    "type": "string",
    "label": "Anchored Data Hash Algorithm",
    "description": "Hashing algorithm used to generate anchoredDataHash (e.g., 'sha3-256').",
    "required": false,
    "placeholder": "Enter anchoreddataalgorithm"
  },
  {
    "name": "anchoredDataHash",
    "type": "string",
    "label": "Anchored Data Hash",
    "description": "Cryptographic hash of the content located at anchoredDataURL.",
    "required": false,
    "placeholder": "Enter anchoreddatahash"
  },
  {
    "name": "assessor",
    "type": "string",
    "label": "Assessor ID",
    "description": "DID of the authorized assessor (test lab, auditor) who evaluated the subject.",
    "required": true,
    "placeholder": "Enter assessor"
  },
  {
    "name": "assessorMetadataURI",
    "type": "uri",
    "label": "Assessor Informational URI",
    "description": "Optional URI with human-readable info about the assessor (e.g., homepage, credentials).",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "certificationLevel",
    "type": "string",
    "label": "Certification Level",
    "description": "Optional classification level of certification (e.g., 'Gold', 'Level 2').",
    "required": false,
    "placeholder": "Enter certificationlevel"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Software Version",
    "description": "Software version of the certified subject.",
    "required": false,
    "placeholder": "Enter version"
  },
  {
    "name": "versionHW",
    "type": "string",
    "label": "Hardware Version",
    "description": "Hardware version of the certified subject, if applicable.",
    "required": false,
    "placeholder": "Enter versionhw"
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Unix timestamp (in seconds) when the certification becomes effective.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional expiration timestamp (in seconds).",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Optional timestamp (in seconds) when the certification was issued.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "attestationType",
    "type": "string",
    "label": "Attestation Type",
    "description": "Optional label (e.g., 'Certification') to help downstream tools interpret this attestation.",
    "required": false,
    "placeholder": "Enter attestationtype"
  }
]

const endorsementFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the entity being endorsed or approved.",
    "required": true,
    "placeholder": "Enter subject"
  },
  {
    "name": "purpose",
    "type": "string",
    "label": "Purpose",
    "description": "Optional short string indicating the reason or context of the endorsement or approval.",
    "required": false,
    "placeholder": "Enter purpose"
  },
  {
    "name": "version",
    "type": "string",
    "label": "Subject Version",
    "description": "Optional semantic version of the subject being endorsed.",
    "required": false,
    "placeholder": "Enter version"
  },
  {
    "name": "attestationType",
    "type": "string",
    "label": "Attestation Type",
    "description": "Distinguishes attestation purpose. Use 'Endorsement' for informal support or 'Approval' for formal recognition.",
    "required": false,
    "placeholder": "Enter attestationtype"
  },
  {
    "name": "policyURI",
    "type": "uri",
    "label": "Policy URI",
    "description": "Optional URI pointing to the criteria or process used for formal approvals.",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "effectiveAt",
    "type": "integer",
    "label": "Effective Date",
    "description": "Optional Unix timestamp when the endorsement or approval becomes effective.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional Unix timestamp after which the endorsement or approval expires.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Optional Unix timestamp for when the attestation was issued.",
    "required": false,
    "placeholder": "0"
  }
]

const linkedIdentifierFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID of the subject (such as did:pkh for wallet addresses or did:web for web domains) that is claimed to control the linked identifier.",
    "required": true,
    "placeholder": "Enter subject"
  },
  {
    "name": "linkedId",
    "type": "string",
    "label": "Linked Identifier",
    "description": "The identifier being claimed as controlled by the subject (e.g., a did:web, email address, or domain).",
    "required": true,
    "placeholder": "Enter linkedid"
  },
  {
    "name": "linkedIdType",
    "type": "string",
    "label": "Linked ID Type",
    "description": "Type or namespace of the linkedId being asserted.",
    "required": true,
    "placeholder": "Enter linkedidtype"
  },
  {
    "name": "method",
    "type": "enum",
    "label": "Verification Method",
    "description": "Verification method used by the attester to confirm the subject's control of the linkedId.",
    "required": true,
    "placeholder": "Enter method",
    "options": [
      "http-file",
      "dns-txt",
      "email-challenge",
      "social-post",
      "manual",
      "oauth",
      "other"
    ]
  },
  {
    "name": "issuedAt",
    "type": "datetime",
    "label": "Issued Date",
    "description": "Timestamp when the attestation was issued.",
    "required": true,
    "placeholder": "2024-01-01T00:00:00Z",
    "format": "date-time"
  },
  {
    "name": "validUntil",
    "type": "datetime",
    "label": "Valid Until",
    "description": "Optional expiration timestamp after which the attestation is no longer considered valid.",
    "required": false,
    "placeholder": "2024-01-01T00:00:00Z",
    "format": "date-time"
  },
  {
    "name": "attestationType",
    "type": "string",
    "label": "Attestation Type",
    "description": "Optional classification of the attestation for filtering and indexing purposes.",
    "required": false,
    "placeholder": "Enter attestationtype"
  }
]

const userReviewFields: FormField[] = [
  {
    "name": "subject",
    "type": "string",
    "label": "Subject ID",
    "description": "DID or URI of the thing being reviewed.",
    "required": true,
    "placeholder": "Enter subject"
  },
  {
    "name": "version",
    "type": "string",
    "label": "SubjectVersion",
    "description": "Version of the reviewed subject (e.g., app version).",
    "required": false,
    "placeholder": "Enter version"
  },
  {
    "name": "summary",
    "type": "string",
    "label": "Review Summary",
    "description": "Short title or headline for the review (e.g., 'Loved it', 'Buggy experience').",
    "required": false,
    "placeholder": "Enter summary"
  },
  {
    "name": "reviewBody",
    "type": "string",
    "label": "Review",
    "description": "Free-form text describing the user's experience or feedback.",
    "required": false,
    "placeholder": "Enter reviewbody"
  },
  {
    "name": "author",
    "type": "string",
    "label": "Author ID",
    "description": "DID, handle, or name of the user who wrote the review.",
    "required": false,
    "placeholder": "Enter author"
  },
  {
    "name": "datePublished",
    "type": "datetime",
    "label": "Date Published",
    "description": "Timestamp when the review was written or published, in ISO 8601 format.",
    "required": false,
    "placeholder": "2024-01-01T00:00:00Z",
    "format": "date-time"
  },
  {
    "name": "ratingValue",
    "type": "integer",
    "label": "Rating",
    "description": "Numerical rating from 1 (worst) to 5 (best).",
    "required": true,
    "placeholder": "0",
    "min": 1,
    "max": 5
  },
  {
    "name": "screenshotUrls",
    "type": "array",
    "label": "Screenshots",
    "description": "Optional screenshots showing the app during review.",
    "required": false,
    "placeholder": "Enter screenshoturls"
  },
  {
    "name": "anchoredDataURL",
    "type": "uri",
    "label": "Anchored Data URL",
    "description": "URI pointing to offchain review content (e.g., IPFS, Cloudinary, Arweave).",
    "required": false,
    "placeholder": "https://example.com",
    "format": "uri"
  },
  {
    "name": "anchoredDataAlgorithm",
    "type": "string",
    "label": "Anchored Data Hash Algorithm",
    "description": "Hashing algorithm used for 'anchoredDataHash' (e.g., 'sha3-256').",
    "required": false,
    "placeholder": "Enter anchoreddataalgorithm"
  },
  {
    "name": "anchoredDataHash",
    "type": "string",
    "label": "Anchored Data Hash",
    "description": "Cryptographic hash of the content located at 'anchoredDataURL'.",
    "required": false,
    "placeholder": "Enter anchoreddatahash"
  },
  {
    "name": "attestationType",
    "type": "string",
    "label": "Attestation Type",
    "description": "Type identifier for this attestation (e.g., 'UserReview').",
    "required": false,
    "placeholder": "Enter attestationtype"
  },
  {
    "name": "issuedAt",
    "type": "integer",
    "label": "Issued Date",
    "description": "Unix timestamp (in seconds) for when the review was submitted.",
    "required": false,
    "placeholder": "0"
  },
  {
    "name": "expiresAt",
    "type": "integer",
    "label": "Expiration Date",
    "description": "Optional expiration timestamp for the attestation.",
    "required": false,
    "placeholder": "0"
  }
]

// Schema definitions
export const certificationSchema: AttestationSchema = {
  id: 'certification',
  title: 'Certification',
  description: 'A flat schema for certifying that a subject has met the requirements of a defined certification program. Anchors immutable program data and supports optional subject and assessor metadata.',
  fields: certificationFields,
  deployedUIDs: {
    97: '0xbb9e58a64550b7956561e9c9266e0a0747fc80c40bd57bb2637be7f8f2817bf7', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000'  // BSC Mainnet
  },
  deployedBlocks: {
    97: 52415269, // BSC Testnet
    56: 0  // BSC Mainnet
  }
};

export const endorsementSchema: AttestationSchema = {
  id: 'endorsement',
  title: 'Endorsement',
  description: 'A lightweight attestation indicating support, trust, or approval for a DID-identified subject. The \'attestationType\' field may be used to distinguish informal endorsements from formal approvals.',
  fields: endorsementFields,
  deployedUIDs: {
    97: '0xda787e2c5b89cd1b2c77d7a9565573cc89bac752e9b587f3348e85c62d606a68', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000'  // BSC Mainnet
  },
  deployedBlocks: {
    97: 52288891, // BSC Testnet
    56: 0  // BSC Mainnet
  }
};

export const linkedIdentifierSchema: AttestationSchema = {
  id: 'linked-identifier',
  title: 'Linked Identifier Attestation (Third-Party Certified)',
  description: 'An attestation where the attester (a trusted third party) asserts that the subject controls the linked identifier, effectively attesting that two identities are owned by the same entity.',
  fields: linkedIdentifierFields,
  deployedUIDs: {
    97: '0xd6ef74f4f2f8d79a8993132577713ada1ae9ba937d8bbd69a174cd6afe6beef6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000'  // BSC Mainnet
  },
  deployedBlocks: {
    97: 52415311, // BSC Testnet
    56: 0  // BSC Mainnet
  }
};

export const userReviewSchema: AttestationSchema = {
  id: 'user-review',
  title: 'UserReview',
  description: 'A flat schema for structured 1–5 star reviews of tokenized applications or digital services. Designed for onchain attestation and offchain anchoring.',
  fields: userReviewFields,
  deployedUIDs: {
    97: '0x21deb2c39c4899b39d3f4af965d455be97862c6be18ffd2c15dbd74aaf50a5f6', // BSC Testnet
    56: '0x0000000000000000000000000000000000000000000000000000000000000000'  // BSC Mainnet
  },
  deployedBlocks: {
    97: 52291400, // BSC Testnet
    56: 0  // BSC Mainnet
  }
};

// Export all schemas
const allSchemas: AttestationSchema[] = [
  certificationSchema,
  endorsementSchema,
  linkedIdentifierSchema,
  userReviewSchema
]

export function getSchema(id: string): AttestationSchema | undefined {
  return allSchemas.find(schema => schema.id === id)
}

export function getSchemaIds(): string[] {
  return allSchemas.map(schema => schema.id)
}

export function getAllSchemas(): AttestationSchema[] {
  return allSchemas
}
